---
- name: Apache webserver configuration
  hosts: node1
  become: true
  tasks:
          - name: Installing Apache latest package
            yum:
                    name: httpd
                    state: latest
          - name: Start and enable Apache service
            service:
                    name: httpd
                    state: started
                    enabled: true
          - name: Configure Apache web page
            template:
                    src: /home/jainab/index.j2
                    dest: /var/www/html/index.html
          - name: Restarting Apache service
            service:
                    name: httpd
                    state: restarted
          - name: Allowing http traffic in Firewall
            firewalld:
                    service: http
                    permanent: yes
                    state: enabled
          - name: Reload Firewall service 
            service:
                    name: firewalld
                    state: reloaded
                 


